'use strict';
const EXP_KEY='south-island-expedition-v1';
const places=[
 {id:'rohan',name:'Mount Sunday',x:72,y:40,links:[1,2],item:'山丘拓印',scene:'风掠过孤丘。残缺的旅行卷上，王城只留下一个轮廓。',choices:['登上观景高处，描下山丘','留在河谷，记录河流走向']},
 {id:'lakes',name:'特卡波',x:61,y:48,links:[0,2,5],item:'星空罗盘',scene:'湖畔营地安静下来。你可以等待夜色，也可以沿岸寻找冰川留下的线索。',choices:['等星光亮起，校准罗盘','观察湖水，记录冰川线索']},
 {id:'aoraki',name:'Aoraki',x:51,y:40,links:[0,1,6],item:'雪山手记',scene:'山峰从云里露出一角。旅人递来两页手记，一页记录名字，一页描画岩层。',choices:['听旅人讲山的名字','画下山脊与岩层']},
 {id:'glenorchy',name:'格林诺奇',x:35,y:63,links:[4,5,6],item:'森林书签',scene:'林间岔路旁，一张书签夹在旅行册里。远处的湖光指向来路。',choices:['沿林缘辨认电影场景','沿湖岸画出方位']},
 {id:'fiord',name:'米尔福德',x:19,y:72,links:[3,5],item:'峡湾素描',scene:'雨线落入深色水面。你展开画纸，试着想象冰川曾经填满山谷。',choices:['描下陡壁与谷形','安静观察岸边生灵']},
 {id:'arrow',name:'箭镇',x:47,y:69,links:[1,3,4],item:'旅人家书',scene:'旧聚居地的故事让旅程慢了下来。远行者的家书里，有金矿，也有想念。',choices:['阅读移民生活的记录','寻找商店与小屋的故事']},
 {id:'west',name:'西海岸',x:38,y:33,links:[2,3,7],item:'雨林札记',scene:'山的另一侧，潮湿的空气包围森林。你想在手册中留下什么？',choices:['记录山两侧的气候','了解绿石的文化意义']},
 {id:'nelson',name:'尼尔森',x:64,y:14,links:[6],item:'铸戒印记',scene:'远征卷的最后一角通向工坊。锤声提醒你，银幕里的传奇也来自真实的手艺。',choices:['了解魔戒的制作工艺','绘下北端海岸的轮廓']}
];
const freshExp=()=>({at:0,energy:6,day:1,visited:[],items:[],journal:[],pending:null,story:'start',trust:0,torch:false,endings:[],challenge:null});
let expedition=freshExp();try{const a=JSON.parse(localStorage.getItem(EXP_KEY));if(a&&Array.isArray(a.visited)&&Number.isInteger(a.at)&&places[a.at])expedition={...freshExp(),...a};}catch{}
function saveExp(){try{localStorage.setItem(EXP_KEY,JSON.stringify(expedition));}catch{toast('浏览器未能保存探险进度。');}}
function expHead(k,t,p){return `<div class="page-title"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></div>`;}
function home(){const modes=[['exp-map','compass','I','南岛远征','循着古道，唤醒沉睡的地图。',`${expedition.visited.length} / 8 处见闻`,'开启远征'],['exp-story','tower','II','中土奇遇','一盏提灯，三个命运的回响。',`${expedition.endings.length} / 3 种结局`,'步入故事'],['exp-challenge','star','III','寻路挑战','读懂风景，寻回星图上的坐标。','五站寻踪 · 地图解谜','追寻星迹'],['academy','book','IV','旅人学堂','翻开古卷，让远方有迹可循。',`${saved.mastered.length} / 48 个发现`,'翻开手稿']];return `<section class="hero portal-hero">${embers()}<div class="portal-top"><span>THE CHRONICLES OF MIDDLE-EARTH</span><i>✦</i><small>南 岛 · 远 征 之 卷</small></div><div class="hero-content"><div class="hero-divider" aria-hidden="true">──── ✧ ────</div><h1>越过山海<br><em>步入传奇</em></h1><p>让古老的光，照亮下一段旅程。</p><button class="primary" data-action="exp-map">${expedition.visited.length?'继续我的远征':'启程 · 南岛远征'} <span>↗</span></button><small class="art-caption">向下探索南岛旅程 <span>↓</span></small></div></section><button class="culture-portal" data-action="cu-open"><span class="culture-portal-mark">${sigil("book")}</span><span class="culture-portal-copy"><small>NEW CHAPTER · PEOPLE OF AOTEAROA</small><strong>走近新西兰</strong><p>跟着小奇，去文化小岛玩。<br>历史剧场 · 拼图修复 · 做客厨房</p></span><span aria-hidden="true">↗</span></button><section class="pathways"><div class="section-heading"><span>CHOOSE YOUR PATH</span><h2>四条道路，一段传奇</h2><div aria-hidden="true">◇</div></div><div class="mode-grid">${modes.map(([a,icon,num,t,d,n,cta])=>`<button class="mode-card" data-action="${a}"><span class="portal-number">${num}</span><span class="mode-symbol">${sigil(icon)}</span><h2>${t}</h2><p>${d}</p><small>${n}</small><span class="mode-enter">${cta} <b>↗</b></span></button>`).join('')}</div></section><div class="journey-summary"><span>✧</span><p>地图上的每一处光，<br>都是你与这片土地的相遇。</p></div><p class="mini home-note">进度保存在本机 · 游戏地图不用于实际导航</p>`;}

function atlas(clickable=true,hideNames=false){const e=expedition;return `<div class="atlas" aria-label="南岛游戏示意地图"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path class="island" d="M71 5 L80 15 73 24 83 29 78 40 70 48 64 59 57 73 46 81 32 89 19 91 10 83 13 71 23 58 31 49 37 37 45 29 53 21 59 10Z"/>${places.flatMap((n,i)=>n.links.filter(j=>j>i).map(j=>`<path class="trail ${i===e.at||j===e.at?'available':''} ${selectedPlace!==null&&((i===e.at&&j===selectedPlace)||(j===e.at&&i===selectedPlace))?'selected-trail':''}" d="M${n.x} ${n.y} L${places[j].x} ${places[j].y}"/>`)).join('')}${hideNames?'':places.map((n,i)=>e.visited.includes(i)?'':`<ellipse cx="${n.x}" cy="${n.y}" rx="11" ry="9" fill="#c4c9b1" opacity=".17"/>`).join('')}<text x="7" y="22">西 海 岸</text><text x="68" y="84">太 平 洋</text></svg>${places.map((n,i)=>`<button class="map-pin ${e.visited.includes(i)?'discovered':''} ${i===e.at?'here':''} ${selectedPlace===i?'selected':''} ${places[e.at].links.includes(i)?'reachable':''}" style="left:${n.x}%;top:${n.y}%" data-action="${hideNames?'exp-guess':clickable?'exp-select':'exp-none'}" data-index="${i}" aria-label="${hideNames?'标记 '+(i+1):n.name}"><b>${hideNames?i+1:e.visited.includes(i)?'✧':'◈'}</b>${hideNames?'':`<span>${n.name}</span>`}</button>`).join('')}<span class="map-legend">N ↑ · 非比例示意图</span></div>`;}
let selectedPlace=null;
function mapPage(){const e=expedition,n=places[e.at],target=selectedPlace===null?null:places[selectedPlace];return expHead('THE SOUTHERN EXPEDITION','南岛远征',`第 ${e.day} 天 · 体力 ${e.energy}/6 · 发现 ${e.visited.length}/8`)+atlas()+`<section class="reading"><span class="eyebrow">${e.visited.length===8?'远征卷已集齐':'当前位置'}</span><h2>${n.name}</h2>${e.pending?`<p>${n.scene}</p><div class="button-stack">${n.choices.map((t,i)=>`<button class="secondary" data-action="exp-explore" data-index="${i}">${t} →</button>`).join('')}</div>`:`<p>${e.visited.includes(e.at)?'这一站的发现已收入行囊。点地图选择下一站，或在营地恢复体力。':'探索这一站，选择你的观察方式，获得独有的旅行物品。'}</p>${!e.visited.includes(e.at)?'<button class="primary" data-action="exp-observe">探索此地 →</button>':''}`}<button class="subtle" data-action="exp-rest">营地休息 · 进入下一天，体力恢复至 6</button></section>${target&&selectedPlace!==e.at?`<section class="reading destination-panel" tabindex="-1"><span class="eyebrow">CHOOSE YOUR WAY</span><h2>前往 ${target.name}</h2>${n.links.includes(selectedPlace)?`<p>选择赶路或观察沿途。景观路线会在日志里留下额外见闻。</p><div class="button-stack"><button class="primary" data-action="exp-travel" data-cost="1">直接前往 · 体力 −1</button><button class="secondary" data-action="exp-travel" data-cost="2">沿途观察 · 体力 −2</button></div>`:'<p>这里还不能直接到达。沿图上的虚线，选择与你当前位置相连的一站。</p>'}</section>`:''}<section class="reading"><h2>行囊 · ${e.items.length} 件</h2><div class="inventory">${e.items.length?e.items.map(i=>`<span>${i}</span>`).join(''):'还没有物品，先探索起点。'}</div>${e.visited.length===8?'<p>你已完成南岛远征！可以继续游历，或去中土奇遇发现不同结局。</p><button class="primary" data-action="exp-story">打开新的故事 →</button>':''}</section><section class="reading"><h2>远征日志</h2>${e.journal.slice(-8).reverse().map(t=>`<p class="journal-line">${t}</p>`).join('')||'<p>旅程从 Mount Sunday 开始。</p>'}</section><p class="mini">迷雾标记 ◈ 代表待探索；金色 ✧ 代表已发现。地点与知识来自旅行学堂，情节为原创虚构。</p>`;}
const storyNodes={
 start:{title:'雾中的信使',text:'一位信使把残缺的星图交给你。天黑前，必须把它送到山谷另一端的观星者手中。你只能先带走一件物品。',choices:[['带上提灯','fork','torch'],['带上给旅人的口粮','fork','trust']]},
 fork:{title:'林间的两条路',text:'左侧的古道通向一座石桥；右侧是一条更短的林间路。风带来了隐约的求助声。',choices:[['走石桥，寻找声音','bridge'],['走林间路，尽快送信','forest']]},
 bridge:{title:'桥边的陌生人',text:'旅人的行囊掉在桥边。他请你帮忙拾回散落的书页。远处的雾越来越浓。',choices:[['停下来帮他整理','help','trust'],['留下方向提示，继续赶路','gate']]},
 help:{title:'多出来的一行字',text:'旅人为你补全星图上的一行注记：真正的入口不在高塔，而在塔下的静水旁。你们结伴继续前行。',choices:[['带着新线索前进','gate']]},
 forest:{title:'树影下的刻痕',text:'岩壁上的刻痕藏在阴影中。提灯可以照清细节；也可以绕开这里，沿脚印前进。',choices:[['举灯寻找刻痕','runes','needTorch'],['沿脚印走出森林','gate']]},
 runes:{title:'静水的秘密',text:'灯光映出一幅倒影图：星空的方向要在水里读。你把这个发现记在星图背面。',choices:[['收好星图，前往谷地','gate','trust']]},
 gate:{title:'星图的终点',text:'山谷里，一座高塔与一湾静水同时映入眼帘。你必须决定把星图送向哪里。',choices:[['去静水旁寻找观星者','water'],['登上高塔发出信号','tower']]},
 water:{title:'静水旁的约定',text:'观星者在水边等候。你带来的不只是星图，还有一路的选择。',ending:'water'},
 tower:{title:'高塔上的火光',text:'你在塔上点亮信号。信使循着光来到谷地，星图终于安全送达。虽然绕了路，你仍完成了约定。',ending:'beacon'}
};
function storyPage(){const e=expedition,n=storyNodes[e.story]||storyNodes.start;let ending=n.ending?(n.ending==='water'?(e.trust>0?'同行者之盟':'孤身观星者'):'高塔守望者'):null;if(ending&&!e.endings.includes(ending)){e.endings.push(ending);saveExp();}return expHead('TALES OF THE WAYFARER','中土奇遇','原创短篇 · 雾谷的星图 · 约 5 分钟')+`<section class="story-scene"><div class="story-emblem">${sigil(n.ending?'star':'tower')}</div><span class="eyebrow">${ending?'结局 · '+ending:'提灯 '+(e.torch?'已携带':'未携带')+' · 羁绊 '+e.trust}</span><h2>${n.title}</h2><p>${n.text}</p>${ending?`<p>${ending==='同行者之盟'?'你一路积累的善意或线索，让星图得到了完整的解读。':ending==='孤身观星者'?'你独自抵达终点，却仍有未解的注记。再试一次，沿路的相遇可能改变结局。':'有时，主动发出的光也是一种找到彼此的方式。'}</p><button class="primary" data-action="exp-story-restart">重走故事，发现另一种结局</button>`:`<div class="button-stack">${n.choices.map(([label,to,effect],i)=>`<button class="secondary" data-action="exp-story-choice" data-index="${i}" ${effect==='needTorch'&&!e.torch?'disabled':''}>${label}${effect==='needTorch'&&!e.torch?'（需要提灯）':''} →</button>`).join('')}</div>`}</section><section class="reading"><h2>结局收藏 ${e.endings.length}/3</h2><p>${e.endings.join(' · ')||'每一次选择，都可能留下不同的旅程。'}</p><button class="subtle" data-action="exp-story-restart">重新开始本篇（保留结局收藏）</button></section><p class="mini">本篇为中土氛围原创故事，不是《指环王》原著情节，也不对应真实步行路线。</p>`;}
const clues=['孤丘曾在电影里托起洛汗王城。你要寻找的不是保存完整的宫殿，而是山丘的轮廓。','这一站与普卡基同在湖泊学习章中，手册提到了星空。请找到特卡波。','一座山拥有两个名字；Ngāi Tahu 的故事赋予它祖先的意义。','从皇后镇沿瓦卡蒂普湖走向北端，你要寻找通往 Paradise 的门户。','冰川留下的陡壁与谷形，如今与海水相遇。','淘金时代的华人聚居地，保存着远渡重洋的生活故事。','翻过南阿尔卑斯山，你来到以雨林与绿石文化为线索的地区。','南岛北端，制作电影魔戒的工坊在这座城市。'];
function challengePage(){const c=expedition.challenge;if(!c)return expHead('READ THE LAND','寻路挑战','读线索，在地图上选择地点。不是选文字答案，而是认识它在南岛的位置。')+`<section class="reading"><h2>五站寻踪</h2><p>每站首次选中得 2 分，第二次选中得 1 分；更多尝试仍可以完成。每次答错都会给你位置提示。</p><button class="primary" data-action="exp-challenge-start">展开地图 →</button></section>`;if(c.index===c.ids.length)return expHead('JOURNEY COMPLETE','五站已寻回',`本局 ${c.score}/10 分`)+`<section class="reading"><h2>把地名放回风景里。</h2><p>你走过了 ${c.ids.map(i=>places[i].name).join('、')}。</p><button class="primary" data-action="exp-challenge-start">再走一条路线 →</button></section>`;const i=c.ids[c.index];return expHead('FIND THE NEXT LANDMARK',`第 ${c.index+1} / 5 站`,clues[i])+atlas(false,true)+`<section class="reading" aria-live="polite"><p>${c.solved?`✓ 找到了：${places[i].name}。${chapter(places[i].id).note}`:c.tries?`还没找到。提示：它位于图中${places[i].y<35?'上部':places[i].y>60?'下部':'中部'}，${places[i].x<45?'偏左':'偏右'}。再选一个编号。`:'轻点地图中的编号标记，提交你的位置判断。'}</p>${c.solved?'<button class="primary" data-action="exp-challenge-next">下一站 →</button>':''}<small>本局 ${c.score} 分 · 地图为非比例示意图</small></section>`;}
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,e=expedition;if(!a.startsWith('exp-'))return;
 if(a==='exp-map'){selectedPlace=null;go('map');return;}if(a==='exp-story'){go('story');return;}if(a==='exp-challenge'){go('challenge');return;}
 if(a==='exp-select'){selectedPlace=Number(b.dataset.index);render();if(selectedPlace!==e.at)document.querySelector('.destination-panel')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});return;}
 if(a==='exp-observe'){if(!e.visited.includes(e.at))e.pending=true;}
 if(a==='exp-explore'&&e.pending){const n=places[e.at],c=chapter(n.id);e.visited.push(e.at);e.items.push(n.item);e.journal.push(`第 ${e.day} 天 · ${n.name}：${n.choices[Number(b.dataset.index)]}。${c.note}`);e.pending=null;setTimeout(()=>revealRelic(n.item,c.note),80);}
 if(a==='exp-rest'){e.day++;e.energy=6;toast('营地休息完毕，体力已恢复。');}
 if(a==='exp-travel'){const cost=Number(b.dataset.cost);if(!places[e.at].links.includes(selectedPlace))return;if(e.energy<cost){toast('体力不足，先在营地休息。');return;}e.energy-=cost;e.at=selectedPlace;selectedPlace=null;e.pending=!e.visited.includes(e.at);if(cost===2)e.journal.push(`第 ${e.day} 天 · 沿途观察：${chapter(places[e.at].id).note}`);}
 if(a==='exp-story-choice'){const choice=storyNodes[e.story]?.choices?.[Number(b.dataset.index)];if(!choice)return;const [,to,effect]=choice;if(effect==='needTorch'&&!e.torch)return;if(effect==='torch')e.torch=true;if(effect==='trust')e.trust++;e.story=to;}
 if(a==='exp-story-restart'){e.story='start';e.trust=0;e.torch=false;}
 if(a==='exp-challenge-start')e.challenge={ids:shuffle(places.map((_,i)=>i)).slice(0,5),index:0,score:0,tries:0,solved:false};
 if(a==='exp-guess'){const c=e.challenge;if(page!=='challenge'||!c||c.solved||c.index>=5)return;const correct=Number(b.dataset.index)===c.ids[c.index];if(correct){c.score+=Math.max(0,2-c.tries);c.solved=true;}else c.tries++;}
 if(a==='exp-challenge-next'){const c=e.challenge;if(!c?.solved)return;c.index++;c.tries=0;c.solved=false;}
 saveExp();render();
});
