'use strict';
const D=window.GAME_DATA,KEY='south-island-quest-v1',app=document.getElementById('app');
const EMPTY=()=>({mastered:[],wrong:[],completed:[],session:null});
let saved=EMPTY(),storageOK=true,page='home',offlineReady=false,offlineError=false;
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw&&Array.isArray(raw.mastered)&&Array.isArray(raw.wrong)&&Array.isArray(raw.completed)){saved={...EMPTY(),...raw};const ids=new Set(D.questions.map(q=>q.id));saved.mastered=saved.mastered.filter(x=>ids.has(x));saved.wrong=saved.wrong.filter(x=>ids.has(x));if(saved.session&&(!Array.isArray(saved.session.ids)||saved.session.ids.some(x=>!ids.has(x))))saved.session=null;}localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageOK=false;}
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chapter=id=>D.chapters.find(x=>x.id===id),question=id=>D.questions.find(x=>x.id===id);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{storageOK=false;toast('当前浏览器无法保存进度；请使用普通 Safari 页面。');}}
function toast(t){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),4200);}
function go(p){page=p;render();window.scrollTo(0,0);}
function sourceLink(id){const s=D.sources[id];return s?`<a class="source" href="${esc(s.url)}" target="_blank" rel="noopener">来源：${esc(s.title)} ↗（联网阅读）</a>`:'';}
function render(){const previous=app.dataset.page;app.dataset.page=page;document.body.classList.toggle('playing',page==='game');document.querySelectorAll('.bottom-nav button').forEach(b=>{const active=b.dataset.action===page;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const notice=storageOK?'':'<div class="notice">当前无法保存进度。可以继续玩；建议在 Safari 普通浏览模式重新打开。</div>';app.innerHTML=notice+({home:home,culture:culturePage,academy:academy,map:mapPage,story:storyPage,challenge:challengePage,game:game,book:book,review:review,guide:guide,result:result}[page]||home)();if(previous!==page&&effectsEnabled&&!matchMedia('(prefers-reduced-motion: reduce)').matches){app.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'ease-out'});}if(page==='game'&&saved.session?.selected!==null){requestAnimationFrame(()=>document.querySelector('.continue')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}}
function academy(){const next=D.chapters.find(c=>!saved.completed.includes(c.id))||D.chapters[0];return `<section class="hero"><div class="hero-content"><span class="eyebrow">THE LORD OF THE RINGS · SOUTH ISLAND</span><h1>循着魔戒，<br>走进南岛。</h1><p>从洛汗的山丘，到精灵的森林。<br>把电影里的远方，变成你的旅程。</p><button class="primary" data-action="${saved.session?'resume':'start'}" data-id="${next.id}">${saved.session?'继续上次答题':'开始章节学习'} <span aria-hidden="true">↗</span></button><small class="art-caption">《指环王》主题插画 · 南岛知识探险</small></div></section><div class="progress-row"><div class="progress-copy"><strong>${saved.completed.length} / ${D.chapters.length}</strong> 枚旅行印记</div><div class="meter" aria-label="已掌握 ${saved.mastered.length} 题，共 ${D.questions.length} 题"><i style="width:${saved.mastered.length/D.questions.length*100}%"></i></div><div class="progress-copy">已掌握 ${saved.mastered.length} / ${D.questions.length} 题</div></div><div class="section-head"><h2>旅人学堂 · 章节学习</h2><span>自由选关 · 不限时</span></div><div class="chapters">${D.chapters.map((c,i)=>{const qs=D.questions.filter(q=>q.chapter===c.id),n=qs.filter(q=>saved.mastered.includes(q.id)).length;return `<button class="chapter" data-action="start" data-id="${c.id}"><span class="chapter-num">${c.symbol}</span><div><span class="chapter-kicker">CHAPTER ${String(i+1).padStart(2,'0')}</span><h3>${esc(c.title)}</h3><p>${esc(c.place)}</p><p>${esc(c.theme)} · ${n}/${qs.length} 已掌握</p></div><span class="arrow">${saved.completed.includes(c.id)?'✓':'↗'}</span></button>`;}).join('')}</div><button class="quick" data-action="quick"><div><b>随风走一局</b><small>随机 8 题 · 电影、自然与人文混合</small></div><span aria-hidden="true">↗</span></button><p class="mini">章节顺序用于学习，不代表自驾路线。主题中包含少量电影情节。</p>`;}
function start(id,mode='chapter'){let qs=mode==='review'?D.questions.filter(q=>saved.wrong.includes(q.id)):mode==='quick'?shuffle(D.questions).slice(0,8):D.questions.filter(q=>q.chapter===id);if(!qs.length){go('review');return;}saved.session={mode,chapter:id||null,ids:qs.map(q=>q.id),index:0,correct:0,selected:null,order:shuffle([0,1,2,3])};save();go('game');}
function game(){const s=saved.session;if(!s)return home();const q=question(s.ids[s.index]),c=chapter(q.chapter),done=s.selected!==null,correct=s.selected===q.answer;return `<section class="game"><div class="game-top"><button class="back" data-action="home" aria-label="保存进度并返回旅程">‹</button><div class="meter"><i style="width:${s.index/s.ids.length*100}%"></i></div><span>${s.index+1} / ${s.ids.length}</span></div><div class="question-card"><span class="eyebrow">${esc(c.en)} / ${esc(q.type)}</span><h2 id="question-title">${esc(q.q)}</h2><div class="options" role="group" aria-labelledby="question-title">${s.order.map((n,i)=>`<button class="option ${done&&n===q.answer?'correct':''} ${done&&s.selected===n&&n!==q.answer?'wrong':''}" data-action="answer" data-index="${n}" ${done?'disabled':''}><span class="letter">${done&&n===q.answer?'✓':done&&s.selected===n?'×':'ABCD'[i]}</span><span>${esc(q.options[n])}</span></button>`).join('')}</div>${done?`<div class="feedback ${correct?'':'wrong-feedback'}" role="status"><strong>${correct?'答对了，记住这片风景。':'差一点，这次一起记住。'}</strong><p>${esc(q.explain)}</p>${sourceLink(q.source)}</div><button class="primary continue" data-action="next">${s.index===s.ids.length-1?'收好这一段旅程':'继续探险'} →</button>`:''}</div><p class="game-note">${esc(c.place)} · 进度自动保存在这台设备<br>${done?'错题会留在「再想一想」里，答对后自动移出。':'不用抢时间，慢慢想。'}</p></section>`;}
function answer(n){const s=saved.session;if(!s||s.selected!==null||![0,1,2,3].includes(n))return;const q=question(s.ids[s.index]);s.selected=n;if(n===q.answer){s.correct++;saved.mastered=[...new Set([...saved.mastered,q.id])];saved.wrong=saved.wrong.filter(x=>x!==q.id);}else{saved.wrong=[...new Set([...saved.wrong,q.id])];saved.mastered=saved.mastered.filter(x=>x!==q.id);}save();render();}
let lastResult=null;
function next(){const s=saved.session;if(!s||s.selected===null)return;if(s.index===s.ids.length-1){lastResult={...s};if(s.mode==='chapter')saved.completed=[...new Set([...saved.completed,s.chapter])];saved.session=null;save();go('result');}else{s.index++;s.selected=null;s.order=shuffle([0,1,2,3]);save();render();window.scrollTo(0,0);}}
function result(){const r=lastResult;if(!r)return home();const c=chapter(r.chapter);return `<section class="question-card result"><span class="eyebrow">A LITTLE CLOSER TO THE SOUTH</span><div class="medallion">${c?c.symbol:'✧'}</div><h1>${c?'收获一枚旅行印记':'又认识了南岛的一角'}</h1><p>${c?esc(c.card):'不着急，知识会在下一次相遇时变熟悉。'}</p><div class="score">${r.correct}<small> / ${r.ids.length} 答对</small></div><p>${r.correct===r.ids.length?'这一程全对！到现场时，试着认出这些线索。':'答错也算一次发现，回头再想一想就好。'}</p><div class="button-stack"><button class="primary" data-action="${c?'book':'home'}">${c?'看看我的收藏':'回到旅程'}</button>${saved.wrong.length?'<button class="secondary" data-action="review">复习留下的问题</button>':''}<button class="subtle" data-action="home">选择下一段旅程 →</button></div></section>`;}
function book(){return `<div class="page-title"><span class="eyebrow">CHRONICLES OF THE JOURNEY</span><h1>收藏你的中土见闻。</h1><p>完成一章，收获一张景点卡。<br>已收集 ${saved.completed.length} / ${D.chapters.length} 张；当前妙搭入口仍需联网打开。</p></div><div class="cards">${D.chapters.map((c,i)=>{const has=saved.completed.includes(c.id);return `<article class="postcard ${has?'':'locked'}"><div class="card-top"><span class="eyebrow">CHRONICLE ${String(i+1).padStart(2,'0')} · ${has?'已收集':'待发现'}</span><h2>${esc(c.card)}</h2><p>${esc(c.en)}</p></div><div class="card-body">${has?`<p>${esc(c.note)}</p>${sourceLink(c.source)}`:`<p class="small">完成「${esc(c.title)}」，解锁这张旅行卡。</p>`}<div style="margin-top:18px"><button class="secondary" data-action="start" data-id="${c.id}">${has?'重走这一程':'去发现'}</button></div></div></article>`;}).join('')}</div>`;}
function review(){const qs=D.questions.filter(q=>saved.wrong.includes(q.id));return `<div class="page-title"><span class="eyebrow">MEET IT AGAIN</span><h1>再想一想。</h1><p>答错的地方，往往最值得再看一眼。<br>还有 ${qs.length} 个小发现等你重逢。</p></div>${qs.length?`<button class="primary" data-action="review-start">开始复习 ${qs.length} 题 →</button><ul class="lesson-list">${qs.map(q=>`<li><span class="tag">${esc(chapter(q.chapter).place)}</span><p style="margin:10px 0 0">${esc(q.q)}</p></li>`).join('')}</ul>`:'<div class="reading empty"><div class="medallion">✓</div><h2>这里暂时没有错题。</h2><p>去走一段新旅程，或者来一局随机挑战。</p><button class="primary" data-action="quick">随机来 8 题 →</button></div>'}`;}
function guide(){return `<div class="page-title"><span class="eyebrow">READY FOR TAKEOFF</span><h1>把中土旅程放进口袋。</h1><p>添加到主屏幕后，可从专属图标打开游戏。当前妙搭入口仍需联网使用。</p></div><section class="reading"><h2>${offlineReady?'✓ 离线内容已保存':offlineError?'当前入口未能启用离线保存':'正在准备离线内容'}</h2><p>${offlineReady?'本设备已保存完整游戏。出发前，请按下面的步骤做一次飞行模式检查。':offlineError?'浏览器没能安装离线脚本。请确认没有使用无痕浏览，保持联网后点击下方按钮重试。':'保持联网并稍等片刻。若一直未完成，点击下方按钮重试。'}</p><button class="secondary" data-action="check-offline">检查离线包</button><p class="mini" id="offline-detail">${navigator.onLine?'当前设备处于联网状态。':'当前设备处于离线状态。'}</p></section><section class="reading"><h2>iPhone · 添加到主屏幕</h2><ol><li>用 <b>Safari</b> 打开游戏，点「分享」→「添加到主屏幕」。</li><li>确认名称为「飞往中土」，图标为精灵金戒、南岛与银蕨，点「添加」。如果以前添加过旧图标，可移除旧入口后重新添加。</li><li>从主屏幕的新图标打开，保持联网即可游玩。添加到主屏幕不会解除当前妙搭入口的离线限制。</li></ol><small>进度只保存在当前设备和浏览器中，不会跨设备同步。清理网站数据、无痕浏览或系统回收储存空间可能使离线包和进度丢失；出发当天再检查一次。</small></section><section class="reading"><h2>这份手册从哪里来</h2><p>内容以新西兰旅游局、DOC、Ngāi Tahu 和地学机构资料为依据；每道题都有来源。外部来源页需要联网。题目和解析加载后可继续阅读，重新打开仍需联网。</p><p class="mini">这是旅行前的知识小游戏，不是导航或开放状态指南。到访前另查道路、步道和私人土地的最新信息。电影内容为非官方学习介绍。</p><p class="photo-credit">主题插画：AI 原创绘制，非电影剧照、非真实景点照片。原版风景摄影：Tony Hisgett · <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noopener">CC BY 2.0</a> · 经缩小及裁切展示。<a href="https://commons.wikimedia.org/wiki/File:Lake_Wakatipu_on_the_way_to_Glenorchy_1_(31641270856).jpg" target="_blank" rel="noopener">原始照片 ↗</a></p><small>内容核对：2026 年 9 月 · 南岛篇 v6.0 · 中土手记</small></section>`;}
async function checkOffline(silent=false){try{if(!('serviceWorker'in navigator))throw new Error('unsupported');await navigator.serviceWorker.register('./sw.js');const reg=await navigator.serviceWorker.ready;const worker=reg.active;if(!worker)throw new Error('not active');const complete=await new Promise((resolve,reject)=>{const channel=new MessageChannel();const timer=setTimeout(()=>reject(new Error('timeout')),12000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data.ready);};worker.postMessage({type:'CHECK_CACHE'},[channel.port2]);});offlineReady=Boolean(complete);updateStatus();if(page==='guide')render();if(!silent)toast(offlineReady?'完整离线包已保存。请再做一次飞行模式检查。':'内容尚未保存完整，请保持联网后重试。');}catch{offlineReady=false;offlineError=true;updateStatus();if(page==='guide')render();if(!silent)toast('当前入口未能启用离线保存，请查看页面说明。');}}
function updateStatus(){const b=document.getElementById('offline-status');b.textContent=offlineReady?(navigator.onLine?'离线已就绪':'离线游玩中'):'离线未就绪';b.classList.toggle('ready',offlineReady);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(['home','academy','book','review','guide'].includes(a))go(a);else if(a==='start')start(b.dataset.id);else if(a==='quick')start(null,'quick');else if(a==='review-start')start(null,'review');else if(a==='resume')go('game');else if(a==='answer')answer(Number(b.dataset.index));else if(a==='next')next();else if(a==='check-offline')checkOffline();});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('home');});
window.addEventListener('online',()=>checkOffline(true));window.addEventListener('offline',updateStatus);
render();checkOffline(true);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_south_island_progress',description:'读取当前设备的南岛学习进度，不修改游戏。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('No parameters accepted');return{mastered:saved.mastered.length,total:D.questions.length,chaptersCompleted:saved.completed.length,chaptersTotal:D.chapters.length,reviewCount:saved.wrong.length,offlineReady};}});}catch{}}

let hadController=Boolean(navigator.serviceWorker?.controller);navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(hadController){location.reload();}hadController=true;});
