'use strict';
const CD=window.CULTURE_DATA, CULTURE_KEY='south-island-app_17emane35du-culture-v1';
const cultureFresh=()=>({known:[],read:[],done:[],scene:null,timeline:false,pairs:0});
let cultureProgress=cultureFresh(),cultureStorage=true;
try{
 const raw=JSON.parse(localStorage.getItem(CULTURE_KEY)||'null');
 if(raw){
  for(const [key,items] of [['known',CD.phrases],['read',CD.cards],['done',CD.scenes]])cultureProgress[key]=[...new Set((Array.isArray(raw[key])?raw[key]:[]).filter(id=>items.some(x=>x.id===id)))];
  cultureProgress.timeline=raw.timeline===true;
  cultureProgress.pairs=Number.isInteger(raw.pairs)&&raw.pairs>0?raw.pairs:0;
  const s=raw.scene,scene=CD.scenes.find(x=>x.id===s?.id);
  if(scene&&Number.isInteger(s.step)&&s.step>=0&&s.step<=scene.steps.length)cultureProgress.scene={id:s.id,step:s.step};
 }
}catch{cultureStorage=false;}
const cultureUI={tab:'island',group:'问候与邮件',index:0,flipped:false,cardGroup:'全部',sceneFeedback:null,sceneOrder:[],translation:false,timelineOrder:[],timelinePool:null,timelineChecked:false,pairGame:null};
const cultureMail={count:'1',tone:'friendly',recipient:'',sender:'',purpose:'checkin',body:'Could you please confirm the check-in time?\nThank you for your help.'};
const mailBodies={checkin:['确认入住','Could you please confirm the check-in time?\nThank you for your help.','可以请您确认一下入住时间吗？\n谢谢您的帮助。'],recommend:['询问推荐','We are visiting the South Island and enjoy short walks.\nWhat would you recommend around here?','我们正在南岛旅行，喜欢短途散步。\n这附近您有什么推荐？'],thanks:['表达感谢','Thank you for your warm welcome and your helpful suggestions.\nWe really enjoyed our visit.','谢谢您的热情接待和有用的建议。\n我们这次来访非常愉快。']};
function saveCulture(){try{localStorage.setItem(CULTURE_KEY,JSON.stringify(cultureProgress));}catch{cultureStorage=false;toast('文化手册进度未能保存；本次仍可继续使用。');}}
function cultureSource(id){const s=CD.sources[id];return s?`<a class="source" href="${esc(s[1])}" target="_blank" rel="noopener">${esc(s[0])} ↗</a>`:'';}
function cultureButton(a,text,extra=''){return `<button class="secondary" data-action="cu-${a}" ${extra}>${text}</button>`;}
function culturePage(){
 const tabs=[['island','文化小岛','01'],['time','时光剧场','02'],['puzzle','修复拼图','03'],['kitchen','做客厨房','04'],['phrases','随身手册','05']];
 const tools=[['phrases','随身语伴'],['scenes','情景对话'],['email','邮件工坊'],['cards','文化典藏'],['pairs','记忆配对']];
 const inTools=tools.some(t=>t[0]===cultureUI.tab),active=inTools?'phrases':cultureUI.tab;
 const label=(inTools?tools:tabs).find(t=>t[0]===cultureUI.tab)?.[1]||'文化小岛';
 return `<section class="culture-heading world-heading"><div class="world-breadcrumb"><button class="back-link" data-action="home">‹ 返回圣殿</button><span>小奇的南岛文化冒险 · ${worldStampCount()} / 14 枚印记</span></div><span class="eyebrow">AOTEAROA · PEOPLE & STORIES</span><h1>走近新西兰</h1><p>沿着好奇心，走进历史与日常。</p><div class="culture-stamps"><span>${cultureProgress.known.length} / ${CD.phrases.length} 句已记住</span><span>${cultureProgress.done.length} / ${CD.scenes.length} 段对话</span><span>${cultureProgress.read.length} / ${CD.cards.length} 张见闻</span></div></section><nav class="culture-tabs" aria-label="文化小岛栏目">${tabs.map(([id,t,n])=>`<button data-action="cu-tab" data-tab="${id}" ${active===id?'aria-current="page"':''}><small>${n}</small>${t}</button>`).join('')}</nav><section class="culture-content" aria-label="${label}">${!cultureStorage||!worldStorage?'<p class="notice">浏览器暂时无法保存部分文化学习进度。</p>':''}${inTools?`<nav class="handbook-nav" aria-label="随身手册工具">${tools.map(([id,t])=>`<button data-action="cu-tab" data-tool="${id}" ${cultureUI.tab===id?'aria-current="page"':''}>${t}</button>`).join('')}</nav>`:''}${({island:worldMain,time:worldTime,puzzle:worldPuzzle,kitchen:worldKitchen,phrases:culturePhrases,scenes:cultureScenes,email:cultureEmail,cards:cultureCards,pairs:culturePairs})[cultureUI.tab]()}</section><details class="culture-sources"><summary>资料来源与玩法灵感</summary><p>真实文化资料与中土虚构故事分开呈现。小奇与场景为原创插画，旅行句子及对话为自编练习。核对：${CD.checked}。</p><p>互动研究参考 <a href="https://github.com/h5p/h5p-image-hotspots" target="_blank" rel="noopener">H5P Image Hotspots</a> 的场景探索、<a href="https://github.com/flbulgarelli/headbreaker" target="_blank" rel="noopener">Headbreaker</a> 的拼图形式和 <a href="https://github.com/KilledByAPixel/LittleJS" target="_blank" rel="noopener">LittleJS</a> 的轻量游戏与动画思路。本页使用独立实现；原有工具参考 H5P 的翻卡、情境分支与记忆配对。</p><div class="culture-source-list">${Object.keys(CD.sources).map(cultureSource).join('')}</div></details>`;
}
function culturePhraseList(){return CD.phrases.filter(p=>p.group===cultureUI.group);}
function englishVoice(){const voices=window.speechSynthesis?.getVoices()||[];return voices.find(v=>/^en[-_]NZ$/i.test(v.lang))||voices.find(v=>/^en[-_]/i.test(v.lang));}
function voiceCaption(){if(!('speechSynthesis'in window))return '此浏览器不支持朗读，可按文本练习。';const v=englishVoice();return v&&/^en[-_]NZ$/i.test(v.lang)?'设备英语朗读 · 新西兰语音；可用性取决于设备。':'设备英语朗读 · 暂无已加载的新西兰语音，不作为当地口音范本。';}
function culturePhrases(){
 const list=culturePhraseList();cultureUI.index=Math.min(cultureUI.index,list.length-1);const p=list[cultureUI.index],known=cultureProgress.known.includes(p.id);
 return `<div class="culture-intro"><h2>遇见一个词，学会一次交流。</h2><p>先想含义，再翻开卡片。每天记住几句就够。</p></div><div class="culture-filters">${['问候与邮件','本地口语','旅行沟通'].map(g=>`<button data-action="cu-group" data-group="${g}" aria-pressed="${g===cultureUI.group}">${g}</button>`).join('')}</div><article class="phrase-card ${cultureUI.flipped?'is-open':''}"><div class="culture-card-top"><span>${p.lang==='mi'?'TE REO MĀORI · 毛利语':'NEW ZEALAND ENGLISH · 英语'}</span><span>${cultureUI.index+1} / ${list.length}</span></div><button class="phrase-flip" data-action="cu-flip" aria-expanded="${cultureUI.flipped}" aria-controls="phrase-meaning"><span class="phrase-word" lang="${p.lang==='mi'?'mi':'en-NZ'}">${esc(p.text)}</span><span class="phrase-hint">${cultureUI.flipped?'收起释义 ↑':'轻点翻开 · 这句话是什么意思？ ↗'}</span></button>${cultureUI.flipped?`<div id="phrase-meaning" class="phrase-meaning"><h3>${esc(p.zh)}</h3><p lang="en-NZ">${esc(p.en)}</p><div class="pronunciation"><span>${p.lang==='mi'?'分音提示':'读音 / 语块'}</span><strong>${esc(p.sound)}</strong><p>${esc(p.tip)}</p></div><blockquote><span lang="${p.lang==='mi'?'mi':'en-NZ'}">${esc(p.example)}</span><small>${esc(p.translation)}</small></blockquote>${cultureSource(p.source)}</div>`:''}<div class="phrase-actions">${p.lang==='mi'?`<a class="secondary" href="https://maoridictionary.co.nz/search?keywords=${encodeURIComponent(p.text)}" target="_blank" rel="noopener">去 Te Aka 听真人发音 ↗</a>`:cultureButton('speak','▶ 听设备朗读',`data-id="${p.id}" ${'speechSynthesis'in window?'':'disabled'}`)}${cultureButton('known',known?'✓ 已记住':'◇ 记住这句',`data-id="${p.id}" aria-pressed="${known}"`)}</div></article><div class="culture-deck-nav">${cultureButton('prev','← 上一句')}<span>${cultureProgress.known.filter(id=>list.some(p=>p.id===id)).length} / ${list.length} 已记住</span>${cultureButton('next','下一句 →')}</div><p class="culture-note">${p.lang==='mi'?'分音帮助辨认音节，不是中文谐音。真人发音需联网打开词典后，点击相应词条的扬声器。长音符号 ā ē ī ō ū 要保留。':voiceCaption()}</p>${p.lang==='mi'?cultureSource('sounds'):''}`;
}
function cultureScenes(){
 const active=cultureProgress.scene,scene=CD.scenes.find(s=>s.id===active?.id);
 if(!scene)return `<div class="culture-intro"><h2>把会遇到的场景，先走一遍。</h2><p>不用抢时间。选一句回应，看看交流会怎样继续。</p></div><div class="culture-scene-grid">${CD.scenes.map((s,i)=>`<button class="culture-scene-tile" data-action="cu-scene" data-id="${s.id}"><span class="scene-number">0${i+1}</span><span><small>${s.place}</small><strong>${s.title}</strong><em>${cultureProgress.done.includes(s.id)?'✓ 已完成 · 再练一次':s.steps.length+' 轮交流 · 开始练习'}</em></span><b>↗</b></button>`).join('')}</div><p class="culture-note">自编模拟对话。实际交流没有唯一的标准答案；这里练习更清楚、尊重对方的表达。</p>`;
 if(active.step===scene.steps.length)return `<section class="culture-complete"><span class="culture-seal">✧</span><span class="eyebrow">A CONVERSATION TO REMEMBER</span><h2>这一段，你已经会聊了。</h2><p>${esc(scene.title)} · ${scene.steps.length} 轮交流完成</p><div class="dialogue-transcript">${scene.steps.map(s=>{const c=s.choices.find(c=>c[2]);return `<p><small>${esc(s.who)}</small><span lang="en-NZ">${esc(s.en)}</span><small>${esc(s.zh)}</small></p><p class="your-line"><small>你</small><span lang="en-NZ">${esc(c[0])}</span><small>${esc(c[1])}</small></p>`;}).join('')}</div>${cultureButton('scenes-back','选择下一段对话 →')}${cultureSource(scene.source)}</section>`;
 const step=scene.steps[active.step],fb=cultureUI.sceneFeedback;
 if(!cultureUI.sceneOrder.length)cultureUI.sceneOrder=shuffle(step.choices.map((_,i)=>i));
 return `<div class="culture-section-top">${cultureButton('scenes-back','‹ 场景目录')}<span>${active.step+1} / ${scene.steps.length} 轮</span></div><div class="culture-intro"><span class="eyebrow">${esc(scene.place)}</span><h2>${esc(scene.title)}</h2></div><div class="dialogue-bubble"><span>${esc(step.who)}</span><h3 lang="en-NZ">${esc(step.en)}</h3>${cultureUI.translation?`<p>${esc(step.zh)}</p>`:''}<div class="dialogue-tools">${cultureButton('translation',cultureUI.translation?'收起中文':'显示中文')}${!/wharenui/.test(step.en)?cultureButton('speak-scene','▶ 英文朗读',`${'speechSynthesis'in window?'':'disabled'}`):''}</div></div><p class="culture-prompt">你会怎样回应？</p><div class="dialogue-choices">${cultureUI.sceneOrder.map(i=>{const c=step.choices[i];return `<button data-action="cu-choice" data-index="${i}" ${fb?.ok?'disabled':''} class="${fb?.index===i?(fb.ok?'correct':'try-again'):''}"><span lang="en-NZ">${esc(c[0])}</span><small>${esc(c[1])}</small></button>`;}).join('')}</div>${fb?`<div class="culture-feedback ${fb.ok?'success':''}" role="status"><strong>${fb.ok?'✓ 交流继续了':'再试一种说法'}</strong><p>${esc(fb.text)}</p>${fb.ok?`<button class="primary" data-action="cu-scene-next">${active.step+1===scene.steps.length?'收好这段对话':'继续交谈'} →</button>`:''}</div>`:''}<p class="culture-note">${voiceCaption()} · 进度自动保存。</p>${cultureSource(scene.source)}`;
}
function mailGreeting(){const m=cultureMail;return(m.tone==='friendly'?'Kia ora':({'1':'Tēnā koe','2':'Tēnā kōrua','3':'Tēnā koutou'})[m.count])+(m.count==='1'&&m.recipient.trim()?' '+m.recipient.trim():'')+',';}
function mailText(){return `${mailGreeting()}\n\n${cultureMail.body.trim()}\n\nNgā mihi,\n${cultureMail.sender.trim()||'[Your name]'}`;}
function cultureEmail(){const m=cultureMail;return `<div class="culture-intro"><h2>英语邮件里的 Māori 问候。</h2><p>选收件人数与语气，看看问候语如何变化。</p></div><div class="email-workshop"><form class="culture-form" onsubmit="return false"><label>收件人数<select data-mail="count">${[['1','一人'],['2','恰好两人'],['3','三人或更多']].map(([n,t])=>`<option value="${n}" ${m.count===n?'selected':''}>${t}</option>`).join('')}</select></label><label>开头语气<select data-mail="tone"><option value="friendly" ${m.tone==='friendly'?'selected':''}>自然友好 · Kia ora</option><option value="formal" ${m.tone==='formal'?'selected':''}>较为正式 · 按人数称呼</option></select></label><label>收件人名字（单人时可填）<input data-mail="recipient" autocomplete="off" maxlength="80" value="${esc(m.recipient)}" placeholder="例如 Sam"></label><label>你的署名<input data-mail="sender" autocomplete="off" maxlength="80" value="${esc(m.sender)}" placeholder="输入你的名字"></label><label class="full-row">选择练习内容<select data-mail="purpose">${Object.entries(mailBodies).map(([id,[t]])=>`<option value="${id}" ${m.purpose===id?'selected':''}>${t}</option>`).join('')}</select></label><label class="full-row">英文正文（可以修改）<textarea data-mail="body" rows="5" maxlength="3000">${esc(m.body)}</textarea></label></form><section class="email-parchment"><span class="eyebrow">YOUR LETTER</span><pre id="culture-mail-preview" lang="en-NZ">${esc(mailText())}</pre><button class="primary" data-action="cu-copy">复制邮件文字</button><p id="culture-copy-status" role="status"></p></section></div><div class="culture-feedback"><strong id="mail-rule">${mailRule()}</strong><p>结尾 <span lang="mi">Ngā mihi</span> 常用于致意，接近 Regards。复制前补上真实预订信息，确认正文与收件人；这里仅生成文字。</p><details><summary>查看练习正文的中文意思</summary><p id="mail-translation">${esc(mailBodies[m.purpose][2])}</p><small>对应预设范例；手动修改后的正文不会自动翻译。</small></details>${cultureSource('greetings')}</div>`;}
function mailRule(){return cultureMail.tone==='friendly'?'Kia ora：常见友好开头，也可以用于多人问候。':({'1':'Tēnā koe：较正式地问候一人。','2':'Tēnā kōrua：恰好问候两人。','3':'Tēnā koutou：问候三人或更多人。'})[cultureMail.count];}
function cultureCards(){
 const categories=['全部',...new Set(CD.cards.map(c=>c.category))];
 return `<div class="culture-intro"><h2>风景之外，还有人的故事。</h2><p>翻开 ${CD.cards.length} 张见闻卡：历史、信仰、南岛社群与日常生活。</p></div><div class="culture-filters">${categories.map(c=>`<button data-action="cu-card-group" data-group="${c}" aria-pressed="${cultureUI.cardGroup===c}">${c}</button>`).join('')}</div><div class="culture-card-grid">${CD.cards.filter(c=>cultureUI.cardGroup==='全部'||c.category===cultureUI.cardGroup).map(c=>`<details class="culture-story-card"><summary><span class="tag">${c.category}</span><h3>${esc(c.title)}</h3><p>${esc(c.front)}</p><small>展开见闻 ↓</small></summary><div class="culture-story-body"><p>${esc(c.body)}</p><blockquote><span lang="en-NZ">${esc(c.talk)}</span><small>${esc(c.zh)}</small></blockquote>${cultureSource(c.source)}${cultureButton('read',cultureProgress.read.includes(c.id)?'✓ 已收入见闻':'◇ 收入我的见闻',`data-id="${c.id}" aria-pressed="${cultureProgress.read.includes(c.id)}"`)}</div></details>`).join('')}</div>${cultureTimeline()}`;
}
function cultureTimeline(){
 if(!cultureUI.timelinePool)cultureUI.timelinePool=shuffle(CD.timeline.map((_,i)=>i));
 const order=cultureUI.timelineOrder,complete=order.length===CD.timeline.length,correct=complete&&order.every((v,i)=>v===i),checked=cultureUI.timelineChecked;
 return `<section class="culture-timeline"><span class="eyebrow">PUT THE STORIES IN ORDER</span><h2>把历史放回时间里</h2><p>按你认为的先后顺序，依次点选事件。选错顺序可以撤回。</p><div class="timeline-pool">${cultureUI.timelinePool.map(i=>`<button data-action="cu-time-pick" data-index="${i}" ${order.includes(i)||checked?'disabled':''}>${esc(CD.timeline[i].text)}</button>`).join('')}</div><ol class="timeline-chosen">${order.map(i=>`<li><span>${checked?CD.timeline[i].label:'— —'}</span>${esc(CD.timeline[i].text)}</li>`).join('')}</ol><div class="culture-row">${cultureButton('time-undo','撤回一步',`${!order.length||checked?'disabled':''}`)}${cultureButton('time-check','检验时间线',`${!complete||checked?'disabled':''}`)}${cultureButton('time-reset','重新排列')}</div>${checked?`<div class="culture-feedback ${correct?'success':''}" role="status"><strong>${correct?'✓ 五个节点，顺序正确':'有几个事件需要换个位置'}</strong><p>${correct?'从航海定居，到条约、选举权与语言复兴，每一段都值得继续了解。':'可以重试，也可以打开下面的时间线，连同来源一起了解。'}</p></div>`:''}<details class="timeline-reference"><summary>查看完整时间线与来源${cultureProgress.timeline?' · ✓ 已完成':''}</summary>${CD.timeline.map(t=>`<p><b>${t.label}</b> ${esc(t.text)}${cultureSource(t.source)}</p>`).join('')}</details></section>`;
}
function newCulturePairs(){const selected=shuffle(CD.phrases.filter(p=>p.group!=='旅行沟通')).slice(0,4);cultureUI.pairGame={tiles:shuffle(selected.flatMap(p=>[{id:p.id,text:p.text,kind:'word',lang:p.lang},{id:p.id,text:p.zh,kind:'meaning',lang:'zh'}])),open:[],matched:[],turns:0,counted:false};}
function culturePairs(){
 if(!cultureUI.pairGame)newCulturePairs();const g=cultureUI.pairGame,won=g.matched.length===4;
 return `<div class="culture-intro"><h2>翻开两张，认出同一个意思。</h2><p>一张原文，一张中文。把问候与俚语变成熟悉的表达。</p></div><div class="culture-section-top"><span>${g.matched.length} / 4 对 · 翻牌 ${g.turns} 次</span>${cultureButton('pairs-reset','换一组')}</div><div class="culture-pair-grid">${g.tiles.map((t,i)=>{const matched=g.matched.includes(t.id),open=matched||g.open.includes(i);return `<button data-action="cu-pair" data-index="${i}" class="${open?'is-revealed':''} ${matched?'is-matched':''}" ${matched||g.open.includes(i)||g.open.length===2?'disabled':''} aria-label="${open?esc(t.text):(i+1)+' 号未翻开的卡片'}"><small>${open?(matched?'✓ 已配对':t.kind==='word'?'原文':'中文'):String(i+1).padStart(2,'0')}</small><span lang="${t.lang==='mi'?'mi':t.lang==='en'?'en-NZ':'zh-CN'}">${open?esc(t.text):'✧'}</span></button>`;}).join('')}</div><div class="pair-status" role="status">${won?'<strong>✓ 四对都找到了！</strong><p>下一次听到这些词，你会更有把握。</p>':g.open.length===2?'<p>这两张还不是一对。记住位置，再试一次。</p><button class="primary" data-action="cu-pairs-again">收起，继续翻牌</button>':'<p>轻点任意两张卡片；不计时，慢慢记。</p>'}</div><p class="culture-note">已完成 ${cultureProgress.pairs} 组。想知道适用场合与读音，回到「随身语伴」。</p>`;
}
function cultureSpeak(text){if(!('speechSynthesis'in window)){toast('此浏览器不支持设备朗读。');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),v=englishVoice();if(v)u.voice=v;u.lang=v?.lang||'en-NZ';u.rate=.85;u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))toast('设备语音暂不可用。请联网并检查英语语音设置。');};speechSynthesis.speak(u);}
function cultureRefresh(focusSelector){const y=window.scrollY;render();window.scrollTo(0,y);if(focusSelector)document.querySelector(focusSelector)?.focus({preventScroll:true});}
document.addEventListener('click',async event=>{
 const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(!a.startsWith('cu-'))return;
 const ui=cultureUI,p=cultureProgress;
 if(a==='cu-open'){go('culture');return;}
 if(a==='cu-tab'){ui.tab=b.dataset.tab||b.dataset.tool;window.speechSynthesis?.cancel();cultureRefresh(`[data-tab="${ui.tab}"]`);document.querySelector('.culture-tabs')?.scrollIntoView({block:'start'});return;}
 if(a==='cu-group'){ui.group=b.dataset.group;ui.index=0;ui.flipped=false;}
 else if(a==='cu-flip')ui.flipped=!ui.flipped;
 else if(a==='cu-prev'||a==='cu-next'){const length=culturePhraseList().length;ui.index=(ui.index+(a==='cu-next'?1:-1)+length)%length;ui.flipped=false;window.speechSynthesis?.cancel();}
 else if(a==='cu-known'){const id=b.dataset.id;if(!CD.phrases.some(x=>x.id===id))return;p.known=p.known.includes(id)?p.known.filter(x=>x!==id):[...p.known,id];saveCulture();}
 else if(a==='cu-speak'){const phrase=CD.phrases.find(x=>x.id===b.dataset.id);if(phrase?.lang==='en')cultureSpeak(phrase.text);return;}
 else if(a==='cu-scene'){if(!CD.scenes.some(s=>s.id===b.dataset.id))return;p.scene={id:b.dataset.id,step:0};ui.sceneOrder=[];ui.sceneFeedback=null;ui.translation=false;saveCulture();}
 else if(a==='cu-scenes-back'){p.scene=null;ui.sceneOrder=[];ui.sceneFeedback=null;saveCulture();}
 else if(a==='cu-translation')ui.translation=!ui.translation;
 else if(a==='cu-speak-scene'){const s=CD.scenes.find(s=>s.id===p.scene?.id)?.steps[p.scene?.step];if(s&&!/wharenui/.test(s.en))cultureSpeak(s.en);return;}
 else if(a==='cu-choice'){const s=CD.scenes.find(s=>s.id===p.scene?.id)?.steps[p.scene?.step],i=Number(b.dataset.index),c=s?.choices[i];if(!c||ui.sceneFeedback?.ok)return;ui.sceneFeedback={index:i,ok:c[2],text:c[3]};}
 else if(a==='cu-scene-next'){if(!ui.sceneFeedback?.ok)return;const s=CD.scenes.find(s=>s.id===p.scene?.id);if(!s)return;p.scene.step++;ui.sceneOrder=[];ui.sceneFeedback=null;ui.translation=false;if(p.scene.step===s.steps.length&&!p.done.includes(s.id))p.done.push(s.id);saveCulture();}
 else if(a==='cu-copy'){const status=document.querySelector('#culture-copy-status');try{await navigator.clipboard.writeText(mailText());status.textContent='✓ 已复制。粘贴到邮件后再核对、发送。';}catch{const range=document.createRange();range.selectNodeContents(document.querySelector('#culture-mail-preview'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);status.textContent='自动复制不可用，邮件文字已选中；请长按并复制。';}return;}
 else if(a==='cu-card-group')ui.cardGroup=b.dataset.group;
 else if(a==='cu-read'){const id=b.dataset.id;if(!CD.cards.some(x=>x.id===id))return;p.read=p.read.includes(id)?p.read.filter(x=>x!==id):[...p.read,id];saveCulture();b.textContent=p.read.includes(id)?'✓ 已收入见闻':'◇ 收入我的见闻';b.setAttribute('aria-pressed',p.read.includes(id));document.querySelector('.culture-stamps span:last-child').textContent=`${p.read.length} / ${CD.cards.length} 张见闻`;return;}
 else if(a==='cu-time-pick'){const i=Number(b.dataset.index);if(!CD.timeline[i]||ui.timelineOrder.includes(i)||ui.timelineChecked)return;ui.timelineOrder.push(i);}
 else if(a==='cu-time-undo'){if(!ui.timelineChecked)ui.timelineOrder.pop();}
 else if(a==='cu-time-check'){if(ui.timelineOrder.length!==CD.timeline.length)return;ui.timelineChecked=true;if(ui.timelineOrder.every((v,i)=>v===i)){p.timeline=true;saveCulture();}}
 else if(a==='cu-time-reset'){ui.timelineOrder=[];ui.timelineChecked=false;ui.timelinePool=null;}
 else if(a==='cu-pairs-reset')newCulturePairs();
 else if(a==='cu-pairs-again')ui.pairGame.open=[];
 else if(a==='cu-pair'){const g=ui.pairGame,i=Number(b.dataset.index),t=g?.tiles[i];if(!t||g.open.length===2||g.open.includes(i)||g.matched.includes(t.id))return;g.open.push(i);if(g.open.length===2){g.turns++;if(g.tiles[g.open[0]].id===g.tiles[g.open[1]].id){g.matched.push(t.id);g.open=[];if(g.matched.length===4&&!g.counted){g.counted=true;p.pairs++;saveCulture();}}}}
 else return;
 cultureRefresh(a==='cu-flip'?'[data-action="cu-flip"]':undefined);
});
document.addEventListener('input',event=>{
 const field=event.target.dataset.mail;if(!Object.hasOwn(cultureMail,field))return;
 cultureMail[field]=event.target.value;
 if(field==='purpose'){cultureMail.body=mailBodies[cultureMail.purpose][1];document.querySelector('[data-mail="body"]').value=cultureMail.body;document.querySelector('#mail-translation').textContent=mailBodies[cultureMail.purpose][2];}
 document.querySelector('#culture-mail-preview').textContent=mailText();document.querySelector('#mail-rule').textContent=mailRule();document.querySelector('#culture-copy-status').textContent='';
});
window.speechSynthesis?.addEventListener('voiceschanged',()=>{if(typeof page!=='undefined'&&page==='culture'&&cultureUI.tab==='phrases'&&culturePhraseList()[cultureUI.index]?.lang==='en'){const note=document.querySelector('.culture-note');if(note)note.textContent=voiceCaption();}});
