'use strict';
const CW=window.CULTURE_PLAY_DATA,CW_KEY='south-island-app_17emane35du-world-v1';
const freshWorld=()=>({seen:[],puzzles:[],kitchen:[],era:0,puzzle:null,kitchenIndex:0});
let world=freshWorld(),worldStorage=true;
try{const r=JSON.parse(localStorage.getItem(CW_KEY)||'null');if(r){
 const sceneIds=CW.eras.flatMap(e=>e.items.map((_,i)=>e.id+':'+i));
 for(const [key,ids] of [['seen',sceneIds],['puzzles',CW.puzzles.map(p=>p.id)],['kitchen',CW.kitchen.map(k=>k.id)]])world[key]=[...new Set((Array.isArray(r[key])?r[key]:[]).filter(id=>ids.includes(id)))];
 if(Number.isInteger(r.era)&&CW.eras[r.era])world.era=r.era;
 if(Number.isInteger(r.kitchenIndex)&&CW.kitchen[r.kitchenIndex])world.kitchenIndex=r.kitchenIndex;
 const p=r.puzzle;if(p&&CW.puzzles.some(x=>x.id===p.id)&&Array.isArray(p.board)&&p.board.length===9&&new Set(p.board).size===9&&p.board.every(i=>Number.isInteger(i)&&i>=0&&i<9))world.puzzle={id:p.id,board:p.board,moves:Number.isInteger(p.moves)&&p.moves>=0?p.moves:0,best:Number.isInteger(p.best)&&p.best>=0&&p.best<=9?p.best:0};
}}catch{worldStorage=false;}
const worldUI={hotspot:null,selected:null,peek:false,message:'我是小奇。跟我去岛上走走，把每一段故事慢慢听完。',outfit:'scarf',food:[],words:[],served:false,kitchenFeedback:'',wordPool:null};
function saveWorld(){try{localStorage.setItem(CW_KEY,JSON.stringify(world));}catch{worldStorage=false;toast('本次可以继续游玩，但浏览器未能保存新进度。');}}
function worldStampCount(){return CW.eras.filter(e=>e.items.every((_,i)=>world.seen.includes(e.id+':'+i))).length+world.puzzles.length+world.kitchen.length;}
function kiwiSVG(mood='idle'){
 return `<svg class="kiwi kiwi-${mood}" viewBox="0 0 180 160" aria-hidden="true"><ellipse cx="78" cy="143" rx="51" ry="8" fill="#293e4520"/><g class="kiwi-body"><g class="kiwi-foot foot-a"><path d="M60 122v17m0-2-12 3m12-3 10 3" fill="none" stroke="#ae7147" stroke-width="7" stroke-linecap="round"/></g><g class="kiwi-foot foot-b"><path d="M96 122v17m0-2-10 3m10-3 11 3" fill="none" stroke="#ae7147" stroke-width="7" stroke-linecap="round"/></g><ellipse cx="77" cy="88" rx="51" ry="45" fill="#b88456"/><path d="M35 70q18-18 43-15M41 85q14-15 28-13M38 102q14-9 25-8M75 52l4-9 7 10" fill="none" stroke="#dab486" stroke-width="5" stroke-linecap="round"/><ellipse cx="109" cy="69" rx="30" ry="31" fill="#c89b66"/><path d="m132 73 40 17-42-5" fill="#e5b774" stroke="#aa7846" stroke-width="2"/><g class="kiwi-eye"><ellipse cx="119" cy="62" rx="5" ry="6" fill="#273b32"/><circle cx="121" cy="60" r="1.8" fill="#fff9e7"/></g><ellipse cx="120" cy="79" rx="7" ry="4" fill="#dd9382" opacity=".6"/><path d="M90 87q15 12 36-2l-2 13q-20 12-40-2Z" fill="${worldUI.outfit==='sun'?'#d7a53c':'#5e9b8a'}"/><path d="m95 95-8 25 17-6 5-16" fill="${worldUI.outfit==='sun'?'#e4b84f':'#82b8a4'}"/>${worldUI.outfit==='fern'?'<path d="M98 42q-8-22 12-31-9 17-12 31m1-7-9-7m12-2 8-6" fill="none" stroke="#5e9976" stroke-width="5" stroke-linecap="round"/>':''}</g></svg>`;
}
function worldIcon(type){
 const shapes={
 boat:'<path d="M9 42h48L46 54H21Z" fill="#ae7654"/><path d="M32 9v33M34 10l19 26H34Z" fill="#f2dec0" stroke="#805d43" stroke-width="3"/><path d="M12 59q9-5 18 0t22 0" fill="none" stroke="#72afbd" stroke-width="3"/>',
 star:'<path d="m32 6 7 17 19 2-15 13 5 19-16-10-17 10 5-19L6 25l19-2Z" fill="#edc668" stroke="#b5964d" stroke-width="2"/>',
 home:'<path d="M13 29h38v29H13Z" fill="#f0dfbc"/><path d="M6 31 32 9l26 22" fill="#b87562" stroke="#8c6457" stroke-width="3"/><path d="M27 41h12v17H27Z" fill="#739989"/><path d="M17 36h7v9h-7Z" fill="#93bdc7"/>',
 stone:'<path d="m15 45 4-25 20-9 14 16-7 25-22 3Z" fill="#528c6c" stroke="#365f4a" stroke-width="3"/><path d="m20 37 9-17 13-2-8 29" fill="none" stroke="#91bba0" stroke-width="3"/>',
 river:'<path d="M40 3C5 24 61 32 27 43L13 61" fill="none" stroke="#8bc1cc" stroke-width="14"/><path d="M40 3C5 24 61 32 27 43L13 61" fill="none" stroke="#daeff0" stroke-width="3"/>',
 scroll:'<path d="M15 8h36v45H17q-9 0-9-7V14q0-6 7-6Z" fill="#f7e6b8" stroke="#b9a275" stroke-width="2"/><path d="M17 8v36M23 20h20M23 28h17M23 36h20M9 46h39" stroke="#b9a275" stroke-width="3"/>',
 pen:'<path d="M14 54 44 9l10 7-31 43-12 3Z" fill="#80a4a8" stroke="#405c60" stroke-width="2"/><path d="m14 54 9 5-12 3Z" fill="#53544a"/>',
 book:'<path d="M7 12q16-5 25 3 11-8 25-3v40q-14-4-25 3-11-7-25-3Z" fill="#f0dbab" stroke="#946d45" stroke-width="3"/><path d="M32 15v40M13 23l12 2m-12 7 12 2m14-9 12-2m-12 11 12-2" stroke="#b49162" stroke-width="2"/>',
 letter:'<rect x="7" y="16" width="50" height="35" rx="4" fill="#f8e9c6" stroke="#c3a679" stroke-width="2"/><path d="m8 18 24 21 24-21M9 50l17-15m29 15L39 35" fill="none" stroke="#c3a679" stroke-width="2"/><circle cx="33" cy="35" r="5" fill="#b47867"/>',
 box:'<path d="M12 27h40v29H12Z" fill="#90aaa6" stroke="#577b79" stroke-width="2"/><path d="m12 27 9-9h23l8 9Z" fill="#b2cbc3"/><path d="M25 23h14" stroke="#385d5b" stroke-width="3"/><path d="m26 7 16 5-5 16-16-5Z" fill="#f4e2b9"/>',
 door:'<path d="M13 60V27a19 19 0 0 1 38 0v33" fill="#b17f55" stroke="#785738" stroke-width="5"/><path d="M21 59V29a11 11 0 0 1 22 0v30" fill="#e6c78c"/><circle cx="38" cy="41" r="3" fill="#866641"/>',
 mountain:'<path d="m4 57 23-43 11 20 8-14 16 37Z" fill="#789fa2"/><path d="m16 35 11-21 11 20-9-5-5 6Z" fill="#fff4dd"/>',
 plate:'<ellipse cx="32" cy="35" rx="27" ry="18" fill="#edf0d6" stroke="#a8b5a0" stroke-width="3"/><ellipse cx="32" cy="35" rx="19" ry="11" fill="none" stroke="#c3cbb7" stroke-width="2"/>',
 leaf:'<ellipse cx="32" cy="45" rx="26" ry="13" fill="#f4e7cb"/><path d="M12 36q-1-23 19-12 16-25 23-1 15 21-16 22-22 9-26-9Z" fill="#88ac68"/><circle cx="22" cy="33" r="6" fill="#cf8070"/><circle cx="44" cy="36" r="5" fill="#e4b66b"/>',
 bread:'<path d="M8 39q-5-20 15-21 7-17 26-1 17 3 9 25-22 14-50-3Z" fill="#d9a661" stroke="#b38247" stroke-width="2"/><path d="m21 24 6 11m8-17 6 15m6-10 5 10" stroke="#f6d39b" stroke-width="5" stroke-linecap="round"/>',
 fruit:'<path d="M30 20q-17-8-22 9-3 22 20 25 23 0 28-21 0-20-24-13" fill="#ca8272"/><path d="M30 22 33 8q13-5 17 2-7 11-18 6" fill="#87a667" stroke="#66854e" stroke-width="3"/><circle cx="20" cy="31" r="4" fill="#e9b5a0"/>',
 flower:'<path d="M31 31v30m0-9L15 39m16 7 14-12" stroke="#83a879" stroke-width="4"/><g fill="#cf8f88"><circle cx="21" cy="17" r="10"/><circle cx="39" cy="17" r="10"/><circle cx="41" cy="33" r="10"/><circle cx="23" cy="34" r="10"/></g><circle cx="31" cy="26" r="9" fill="#edc16c"/>',
 fish:'<path d="M8 32q21-25 38-4l14-13v34L46 36Q25 56 8 32Z" fill="#86b2b7" stroke="#4c858c" stroke-width="2"/><circle cx="19" cy="29" r="3" fill="#34545a"/>',
 chicken:'<path d="m12 53 16-19" stroke="#eadbc0" stroke-width="10" stroke-linecap="round"/><ellipse cx="39" cy="24" rx="18" ry="16" transform="rotate(-40 39 24)" fill="#c88c61"/><path d="m39 15 9 12" stroke="#e6b991" stroke-width="4" stroke-linecap="round"/>'
 };
 return `<svg viewBox="0 0 64 64" aria-hidden="true">${shapes[type]||shapes.book}</svg>`;
}
function worldArt(kind='land'){
 const night=kind==='sea'||kind==='festival',sky=night?'#244858':'#d1e4d8';
 let middle=kind==='sea'?'<path d="M0 200Q110 170 230 210T600 180V400H0" fill="#6cabb0"/><path d="M0 253q110-35 250 0t350-10M0 325q160-35 290 0t310 0" fill="none" stroke="#a9d7d1" stroke-width="8"/><g transform="translate(150 140) scale(3.3)">'+worldIcon('boat').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g>':kind==='town'?'<path d="M0 315 600 250v150H0" fill="#c6b195"/><path d="m0 375 600-57" stroke="#ecd3a7" stroke-width="25"/><g transform="translate(65 130) scale(2.5)">'+worldIcon('home').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g><g transform="translate(270 115) scale(2.1)">'+worldIcon('home').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g><g transform="translate(440 145) scale(1.5)">'+worldIcon('home').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g>':'<path d="M0 290Q180 185 290 280T600 270V400H0" fill="#91b39b"/><path d="M260 240q-70 58 8 77t-9 83" fill="none" stroke="#cfdbc2" stroke-width="38"/><g transform="translate(365 175) scale(1.8)">'+worldIcon('home').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g><g transform="translate(60 290)">'+worldIcon('flower').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g><g transform="translate(480 315) scale(.7)">'+worldIcon('flower').replace(/<svg[^>]*>|<\/svg>/g,'')+'</g>';
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400" aria-hidden="true"><rect width="600" height="400" fill="${sky}"/><circle cx="465" cy="70" r="35" fill="${night?'#f4e6b3':'#f3cf80'}"/>${night?'<g fill="#f4dfa2"><circle cx="78" cy="42" r="3"/><circle cx="183" cy="80" r="4"/><circle cx="320" cy="40" r="3"/><circle cx="363" cy="115" r="3"/><circle cx="528" cy="135" r="4"/></g>':'<g fill="#f5f1dd" opacity=".8"><ellipse cx="115" cy="60" rx="57" ry="17"/><ellipse cx="142" cy="51" rx="28" ry="22"/><ellipse cx="339" cy="94" rx="54" ry="14"/></g>'}<path d="m0 222 113-121 97 92 107-135 171 157 112-79v159H0" fill="${night?'#537f88':'#7fa6a3'}"/><path d="m267 120 50-62 63 59-39-12-19 16-18-24-14 23Z" fill="#f4f0dd"/><path d="M0 247q140-100 286 0t314 0v153H0" fill="#5b8979"/>${middle}<g fill="#386a5c"><path d="m40 234 19-65 18 65h-8l15 27H29l16-27Z"/><path d="m528 260 23-81 24 81h-10l16 30h-61l18-30Z"/></g></svg>`;
}
function worldCompanion(message=worldUI.message,mood='idle'){
 return `<div class="kiwi-companion"><button class="kiwi-pet" data-action="cw-pet" aria-label="轻点小奇，听一句鼓励">${kiwiSVG(mood)}</button><div class="kiwi-speech"><small>小奇 · 你的文化向导</small><p role="status">${esc(message)}</p></div></div>`;
}
function worldMain(){const stamps=worldStampCount();return `<div class="world-welcome"><span class="eyebrow">KIKI'S LITTLE CULTURE ISLAND</span><h2>跟着小奇，慢慢认识新西兰。</h2><p>看一幕历史，修复一幅画，再去朋友家做客。</p></div><div class="culture-island" aria-label="文化小岛玩法地图">${worldArt('land')}<span class="island-cloud cloud-one"></span><span class="island-cloud cloud-two"></span><div class="island-guide">${kiwiSVG('walk')}</div><button class="island-stop stop-time" data-action="cw-go" data-tab="time"><span>${worldIcon('book')}</span><b>时光剧场</b><small>8 幕故事</small></button><button class="island-stop stop-puzzle" data-action="cw-go" data-tab="puzzle"><span>${worldIcon('mountain')}</span><b>历史修复台</b><small>3 幅拼图</small></button><button class="island-stop stop-kitchen" data-action="cw-go" data-tab="kitchen"><span>${worldIcon('plate')}</span><b>做客厨房</b><small>准备一场相聚</small></button><button class="island-stop stop-book" data-action="cw-go" data-tab="cards"><span>${worldIcon('scroll')}</span><b>文化典藏</b><small>${CD.cards.length} 篇见闻</small></button><span class="island-caption">想象中的文化小岛 · 轻点建筑出发</span></div>${worldCompanion()}<div class="world-passport"><div><span class="eyebrow">YOUR LITTLE PASSPORT</span><h3>我的旅行印记 <b>${stamps} / 14</b></h3><p>看完一幕、拼好一幅画、完成一次做客练习，就留下一枚印记。</p></div><div class="world-stamps">${CW.eras.map(e=>`<span class="${e.items.every((_,i)=>world.seen.includes(e.id+':'+i))?'earned':''}" title="${esc(e.title)}">${worldIcon(e.items[0].icon)}</span>`).join('')}${CW.puzzles.map(p=>`<span class="${world.puzzles.includes(p.id)?'earned':''}" title="${p.title}">${worldIcon('mountain')}</span>`).join('')}${CW.kitchen.map(k=>`<span class="${world.kitchen.includes(k.id)?'earned':''}" title="${k.title}">${worldIcon('plate')}</span>`).join('')}</div><div class="kiwi-outfits"><span>给小奇换一条围巾</span>${[['scarf','湖绿色'],['sun','暖金色'],['fern','戴一片小叶子']].map(([v,t])=>`<button data-action="cw-outfit" data-outfit="${v}" aria-pressed="${worldUI.outfit===v}">${t}</button>`).join('')}</div></div><button class="world-handbook-link" data-action="cw-go" data-tab="phrases">随身语伴与邮件工坊 <span>原来的工具都在这里 ↗</span></button><p class="culture-note">全部场景随时可玩，不用等解锁。小奇和场景是原创学习插画；具体历史见每个发现的来源。</p>`;}
function worldTime(){const e=CW.eras[world.era],done=e.items.filter((_,i)=>world.seen.includes(e.id+':'+i)).length,selected=e.items[worldUI.hotspot];return `<div class="world-section-head"><div><span class="eyebrow">THE LITTLE TIME THEATRE</span><h2>时光剧场</h2></div><span>${world.era+1} / ${CW.eras.length} 幕</span></div><label class="era-picker">这一幕<select data-world-era>${CW.eras.map((x,i)=>`<option value="${i}" ${world.era===i?'selected':''}>${x.year} · ${x.title}</option>`).join('')}</select></label><div class="era-title"><span>${e.year}</span><h3>${e.title}</h3><p>${e.sub}</p></div><div class="time-stage" aria-label="轻点场景中的三个物件">${worldArt(e.art)}${e.items.map((item,i)=>`<button class="history-hotspot ${world.seen.includes(e.id+':'+i)?'seen':''} ${worldUI.hotspot===i?'selected':''}" style="--spot-x:${item.x}%;--spot-y:${item.y}%" data-action="cw-hotspot" data-index="${i}" aria-label="${esc(item.name)}${world.seen.includes(e.id+':'+i)?'，已探索':''}" aria-pressed="${worldUI.hotspot===i}"><span>${worldIcon(item.icon)}</span><b>${esc(item.name)}</b><i>${world.seen.includes(e.id+':'+i)?'✓':'+'}</i></button>`).join('')}</div><div class="world-scene-status"><span>已发现 ${done} / 3 个故事</span><span>${done===3?'✓ 本幕已阅':'轻点发光物件'}</span></div>${selected?`<article class="history-reveal" aria-live="polite"><span class="eyebrow">${esc(selected.name)}</span><h3>${esc(selected.title)}</h3><p>${esc(selected.text)}</p>${cultureSource(selected.source||e.source)}</article>`:worldCompanion('点点画面里的三个物件，看看它们各自带着什么故事。')}<div class="world-stage-nav"><button data-action="cw-era-prev" ${world.era===0?'disabled':''}>← 上一幕</button><button data-action="cw-era-next" ${world.era===CW.eras.length-1?'disabled':''}>下一幕 →</button></div><p class="culture-note">场景为概念插画，帮助发现线索，不是历史现场的精确复原。纪年与资料可点来源核对。</p>`;}
function newWorldPuzzle(id){let board=shuffle([0,1,2,3,4,5,6,7,8]);if(board.every((n,i)=>n===i))[board[0],board[1]]=[board[1],board[0]];world.puzzle={id,board,moves:0,best:board.filter((n,i)=>n===i).length};worldUI.selected=null;worldUI.peek=false;saveWorld();}
function worldPuzzle(){
 if(!world.puzzle)newWorldPuzzle(CW.puzzles[0].id);const g=world.puzzle,p=CW.puzzles.find(p=>p.id===g.id),correct=g.board.filter((n,i)=>n===i).length,won=correct===9,uri='data:image/svg+xml,'+encodeURIComponent(worldArt(p.art)).replace(/'/g,'%27');
 return `<div class="world-section-head"><div><span class="eyebrow">THE STORY RESTORATION STUDIO</span><h2>历史修复台</h2></div><span>${world.puzzles.length} / 3 幅</span></div><div class="puzzle-choices">${CW.puzzles.map(p=>`<button data-action="cw-puzzle-select" data-id="${p.id}" aria-pressed="${p.id===g.id}">${p.title}${world.puzzles.includes(p.id)?' ✓':''}</button>`).join('')}</div>${worldCompanion(won?'拼好了！再看看画后面的故事，去剧场里继续探索。':worldUI.selected===null?'先点一块碎片，再点另一块，它们就会交换位置。':'选好了。现在点另一块碎片，把它们交换过来。',won?'happy':'idle')}<div class="puzzle-topline"><strong>${p.title}</strong><span>${correct} / 9 就位 · ${g.moves} 步</span></div><div class="restoration-board ${won?'is-complete':''}" aria-label="九块拼图，依次点两块交换">${g.board.map((tile,i)=>`<button data-action="cw-tile" data-index="${i}" aria-label="位置 ${i+1}，碎片 ${tile+1}${worldUI.selected===i?'，已选中':''}" aria-pressed="${worldUI.selected===i}" ${won?'disabled':''} class="${worldUI.selected===i?'chosen':''}" style="background-image:url('${uri}');background-position:${tile%3*50}% ${Math.floor(tile/3)*50}%"><span>${worldUI.peek?tile+1:worldUI.selected===i?'✦':''}</span></button>`).join('')}</div><div class="world-stage-nav"><button data-action="cw-puzzle-peek" aria-pressed="${worldUI.peek}">${worldUI.peek?'收起原图与编号':'看原图与编号'}</button><button data-action="cw-puzzle-reset">重新打乱</button></div>${worldUI.peek?`<div class="puzzle-reference">${worldArt(p.art)}<p>编号从左到右、从上到下为 1—9；不使用提示也可以慢慢拼。</p></div>`:''}<div class="puzzle-findings" aria-live="polite"><h3>${won?'✓ 画面完整了，故事还在继续':'修复中的发现'}</h3>${p.facts.map((f,i)=>`<p class="${g.best>=(i+1)*3?'revealed':'undiscovered'}"><b>${i+1}</b>${g.best>=(i+1)*3?esc(f):`让 ${3*(i+1)} 块碎片就位，展开这条见闻。`}</p>`).join('')}${cultureSource(p.source)}${won?`<button class="primary" data-action="cw-era-link" data-id="${p.era}">走进这段历史 →</button>`:''}</div>`;
}
function worldKitchen(){const k=CW.kitchen[world.kitchenIndex],ui=worldUI;if(k.words&&!ui.wordPool)ui.wordPool=shuffle(k.words.map((_,i)=>i));return `<div class="world-section-head"><div><span class="eyebrow">A LITTLE KINDNESS TO SHARE</span><h2>小奇的做客厨房</h2></div><span>${world.kitchenIndex+1} / 3 站</span></div><div class="kitchen-route">${CW.kitchen.map((x,i)=>`<button data-action="cw-kitchen-level" data-index="${i}" aria-pressed="${i===world.kitchenIndex}">${world.kitchen.includes(x.id)?'✓':i+1} ${['分享','偏好','致谢'][i]}</button>`).join('')}</div>${worldCompanion(ui.served?'心意送到了。这句话，下次见到朋友也用得上。':k.intro,ui.served?'happy':'idle')}<div class="kitchen-invite"><span>朋友的留言</span><h3 lang="en-NZ">${k.en}</h3><p>${k.zh}</p></div>${k.words?`<div class="word-tray" aria-label="已拼好的句子">${ui.words.length?ui.words.map((n,i)=>`<button data-action="cw-word-remove" data-index="${i}" ${ui.served?'disabled':''}>${k.words[n]}</button>`).join(''):'点下面的词块，把感谢拼出来。'}</div><div class="word-pool">${ui.wordPool.map(i=>`<button data-action="cw-word" data-index="${i}" ${ui.words.includes(i)||ui.served?'disabled':''}>${k.words[i]}</button>`).join('')}</div>`:`<div class="sharing-plate"><span class="plate-label">我的分享盘 · ${ui.food.length} / ${k.needed}</span><div>${ui.food.map(id=>`<button data-action="cw-food" data-id="${id}" ${ui.served?'disabled':''} aria-label="移除${CW.food[id][0]}">${worldIcon(CW.food[id][2])}<small>${CW.food[id][0]}</small></button>`).join('')||'<span class="plate-empty">把心意放进盘子里</span>'}</div></div><div class="kitchen-shelf">${k.options.map(id=>`<button data-action="cw-food" data-id="${id}" aria-pressed="${ui.food.includes(id)}" ${ui.served?'disabled':''}>${worldIcon(CW.food[id][2])}<strong>${CW.food[id][0]}</strong><small lang="en-NZ">${CW.food[id][1]}</small></button>`).join('')}</div>`}<div class="kitchen-feedback" role="status">${esc(ui.kitchenFeedback)}</div>${ui.served?`<article class="history-reveal"><h3>✓ ${k.title} · 完成</h3><p>${k.success}</p><blockquote><span lang="en-NZ">${k.phrase}</span><small>${k.translation}</small></blockquote>${cultureSource(k.source)}<button class="primary" data-action="cw-kitchen-next">${world.kitchenIndex<2?'继续这次相聚':'收好做客印记'} →</button></article>`:`<button class="primary kitchen-submit" data-action="cw-serve" ${(k.words?ui.words.length!==k.words.length:ui.food.length!==k.needed)?'disabled':''}>${k.words?'练习说出来':'端上分享盘'} →</button>`}<p class="culture-note">这是虚构朋友间的交流练习。食物图标代表这份练习菜单，实际做客时以对方的具体请求为准。</p>`;}
function resetKitchenUI(){worldUI.food=[];worldUI.words=[];worldUI.wordPool=null;worldUI.served=false;worldUI.kitchenFeedback='';}
function worldRefresh(){const y=scrollY;render();window.scrollTo(0,y);}
function worldNavigate(tab){cultureUI.tab=tab;worldRefresh();document.querySelector('.culture-tabs')?.scrollIntoView({block:'start'});}
document.addEventListener('change',event=>{if(event.target.matches('[data-world-era]')){const i=Number(event.target.value);if(!CW.eras[i])return;world.era=i;worldUI.hotspot=null;saveWorld();worldRefresh();}});
document.addEventListener('click',event=>{
 const b=event.target.closest('[data-action]');if(!b||b.disabled||!b.dataset.action.startsWith('cw-'))return;const a=b.dataset.action,u=worldUI;
 if(a==='cw-go'){worldNavigate(b.dataset.tab);return;}
 if(a==='cw-pet'){const lines=['不赶时间。把好奇心装进口袋就出发。','拼图可以慢慢来，我就在旁边陪你。','同一个地方，可能有不止一种历史叙述。','会问“能再讲一点吗”，就是很好的旅人。'];u.message=lines[Math.floor(Math.random()*lines.length)];const bubble=b.closest('.kiwi-companion')?.querySelector('.kiwi-speech p');if(bubble)bubble.textContent=u.message;b.classList.remove('petted');void b.offsetWidth;b.classList.add('petted');return;}
 if(a==='cw-outfit'){if(['scarf','sun','fern'].includes(b.dataset.outfit))u.outfit=b.dataset.outfit;}
 else if(a==='cw-hotspot'){const e=CW.eras[world.era],i=Number(b.dataset.index);if(!e.items[i])return;u.hotspot=i;const id=e.id+':'+i;if(!world.seen.includes(id)){world.seen.push(id);saveWorld();}}
 else if(a==='cw-era-next'||a==='cw-era-prev'){const n=world.era+(a==='cw-era-next'?1:-1);if(!CW.eras[n])return;world.era=n;u.hotspot=null;saveWorld();}
 else if(a==='cw-era-link'){const i=CW.eras.findIndex(e=>e.id===b.dataset.id);if(i<0)return;world.era=i;u.hotspot=null;saveWorld();worldNavigate('time');return;}
 else if(a==='cw-puzzle-select'){if(!CW.puzzles.some(p=>p.id===b.dataset.id))return;if(world.puzzle?.id!==b.dataset.id)newWorldPuzzle(b.dataset.id);}
 else if(a==='cw-puzzle-reset')newWorldPuzzle(world.puzzle.id);
 else if(a==='cw-puzzle-peek')u.peek=!u.peek;
 else if(a==='cw-tile'){const i=Number(b.dataset.index),p=world.puzzle;if(!p||!Number.isInteger(i)||i<0||i>8||p.board.every((n,j)=>n===j))return;if(u.selected===null)u.selected=i;else if(u.selected===i)u.selected=null;else{[p.board[i],p.board[u.selected]]=[p.board[u.selected],p.board[i]];u.selected=null;p.moves++;const count=p.board.filter((n,j)=>n===j).length;p.best=Math.max(p.best,count);if(count===9&&!world.puzzles.includes(p.id))world.puzzles.push(p.id);saveWorld();}}
 else if(a==='cw-kitchen-level'){const i=Number(b.dataset.index);if(!CW.kitchen[i])return;world.kitchenIndex=i;resetKitchenUI();saveWorld();}
 else if(a==='cw-food'){if(u.served)return;const k=CW.kitchen[world.kitchenIndex],id=b.dataset.id;if(!k.options?.includes(id))return;if(u.food.includes(id))u.food=u.food.filter(x=>x!==id);else if(!k.accept.includes(id)){u.kitchenFeedback=id==='empty'?'Bring a plate 在这里不是带空盘子，选一份分享的食物吧。':id==='flowers'?'花束可以是一份礼物，但这次请你准备的是分享的食物。':'这位朋友这次想吃素食，再看看蔬菜、水果或这份练习中的面包。';}else if(u.food.length<k.needed){u.food.push(id);u.kitchenFeedback='已放入分享盘。点盘中的食物可以拿回来。';}else u.kitchenFeedback='盘子里已有两样。可以先拿回一样，再换新的。';}
 else if(a==='cw-word'){const k=CW.kitchen[world.kitchenIndex],i=Number(b.dataset.index);if(u.served||!k.words?.[i]||u.words.includes(i))return;u.words.push(i);u.kitchenFeedback='';}
 else if(a==='cw-word-remove'){if(u.served)return;u.words.splice(Number(b.dataset.index),1);u.kitchenFeedback='';}
 else if(a==='cw-serve'){const k=CW.kitchen[world.kitchenIndex];if(u.served)return;const valid=k.words?u.words.length===k.words.length&&u.words.every((n,i)=>n===i):u.food.length===k.needed&&u.food.every(id=>k.accept.includes(id));if(!valid){u.kitchenFeedback='再看看语序：先 Thank you，再 for having me。点上面的词块可撤回。';}else{u.served=true;u.kitchenFeedback='';if(!world.kitchen.includes(k.id))world.kitchen.push(k.id);saveWorld();}}
 else if(a==='cw-kitchen-next'){if(!u.served)return;if(world.kitchenIndex<2){world.kitchenIndex++;resetKitchenUI();saveWorld();}else{worldNavigate('island');return;}}
 else return;
 worldRefresh();
 if(a==='cw-hotspot')document.querySelector('.history-reveal')?.scrollIntoView({block:'nearest',behavior:'instant'});
});
